### ISSUE TITLE
BUG:url替换不完全

### ISSUE THREAD

**Issue by breezechen** [Lafeng/AirGoo#35]
比如访问`https://xx.com/!translate.google.com/`
对返回的结果中`href="/.*"`的部分没有执行替换
```
...
<link rel=stylesheet href="/translate/releases/twsfe_w_20151026_RC02/r/css/desktop_ltr.css">
...
```
正确的结果应该是
```
...
<link rel=stylesheet href="https://xx.com/!translate.google.com/translate/releases/twsfe_w_20151026_RC02/r/css/desktop_ltr.css">
...
```

**Comment by vickery** [comment]
没有对translate做过分析、也没有规则，所以难以保证translate反代的可用性。
当时的重点是解决search,image,map这3个的可用，其它都没有过多考虑，也难以完全照顾到。

**Comment by breezechen** [comment]
哦，如果可以做成`https://xx.com/!any_urls`就强大了~

**Comment by vickery** [comment]
如果是无状态资源，事实上`http://xx/!any_urls`是完全可以的，比如直链下载，但往往web应用都是很复杂的，要把无限域映射到有限域下，不光要复杂的替换，还要处理无限域下的状态，比如cookie，因此这个问题只能在有限的人工规则里面实现有限的可用。

**Comment by breezechen** [comment]
感觉能做到所有`href`跟`url`的替换就很神奇了，基本解决80%的问题...

**Comment by breezechen** [comment]
Sorry! 这个Issue不应该我关，作者有打算解决这个Issue么？

**Comment by vickery** [comment]
暂不解决。
